services:
  app:
    container_name: mould_app
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: mould_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mould_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: mould_tracking
      MYSQL_USER: mould_user
      MYSQL_PASSWORD: mould_pass
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Jakarta
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mould_pma
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: mould_user
      PMA_PASSWORD: mould_pass

volumes:
  dbdata:
